{
    "name": "Hospital Management",
    "version": "1.0",
    "summary": "Hospital Management System",
    "author": "Your Name",
    "category": "Management",
    # "depends": ["base"],
    "depends": ["base", "hr", "account"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "reports/appointment_report.xml",
        "reports/appointment_templates.xml",
        "reports/dashboard_report.xml",
        "reports/dashboard_template.xml",
        "views/patient_views.xml",
        "views/doctor_views.xml",
        "views/appointment_views.xml",
        "views/dashboard_views.xml",
        "data/demo_data.xml",
    ],
    "installable": True,
    "application": True,
    "demo": [
        "demo/demo.xml",
    ],
}
